

import { type Metadata } from 'next'
import {ClerkProvider} from '@clerk/nextjs'
import { HeaderActions } from "@/components/ui/header-actions";
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/ui/app-sidebar"

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger className='mt-4 ml-4'/>
          <main className="flex min-h-screen flex-col">            <div className="fixed top-4 right-4 z-50">
              <HeaderActions />
            </div>
            {children}
          </main>
        </SidebarProvider>
      </div>
    </ClerkProvider>
  )
}