import { type Metadata } from 'next'
import {ClerkProvider} from '@clerk/nextjs'
import { HeaderActions } from "@/components/ui/header-actions";
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/ui/app-sidebar"

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <SidebarProvider>
          <AppSidebar />
        <div className='flex flex-col min-h-screen'>
          
          <div className='w-full'>
          <SidebarTrigger className='mt-4 ml-4'/>
              <div className="fixed top-4 right-4 z-50">
                <HeaderActions />
              </div>
          </div>
          <main className="flex min-h-screen flex-col">            
            
            <div>
              {children}

            </div>
          </main>
          </div>
        </SidebarProvider>
      </div>
    </ClerkProvider>
  )
}