
import { type Metadata } from 'next'
import { Navigation } from '@/app/pricing/components/navigation';
import {ClerkProvider} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google';
import 'flowbite';
import Footer from '@/app/pricing/components/footer/footer';
import './globals.css';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Navigation/>
            {children}
            
          <footer className="row-start-2 flex gap-[10px] flex-wrap items-center justify-center">
                <Footer/>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  )
}