import { type Metadata } from 'next'
import { Navigation } from '@/components/navigation';
import {ClerkProvider} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'flowbite';
import Title from '@/components/title';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
           <Navigation/>
           <Title/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}